#!/usr/bin/env bash
# installs nginx on webserver
# changes default webpage to print "Holberton School"
# Update the package index
apt-get update

# Install Nginx
sudo apt-get install -y nginx-core

# Configure Nginx
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location / {
        echo "Hello World!";
    }
}' > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
