#!/usr/bin/env bash
# installs nginx on webserver
# changes default webpage to print "Holberton School"
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
