#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend http_front
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 439479-web-01 52.91.144.190:80
        server 439479-web-02 54.175.133.200:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
